version: '3'
services:
  nextjs-auth-sample-mysql:
    container_name: nextjs-auth-sample-mysql
    build: ./mysql
    volumes:
      - sample_mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default_authentication_plugin=mysql_native_password
    ports:
      - 13306:3306
volumes:
  sample_mysql_volume:
